openapi: 3.2.0
info:
  title: Reclaim User Notification Settings API
  description: Reclaim's awesome API
  contact:
    name: Reclaim.ai Inc.
    url: http://reclaim.ai
    email: info@reclaim.ai
  license:
    name: Reclaim 9.9
    url: http://reclaim.ai
  version: '0.1'
tags:
- name: user-notification-settings
paths:
  /api/notification-settings:
    get:
      tags:
      - user-notification-settings
      operationId: getUserSettings
      responses:
        '200':
          description: getUserSettings 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotificationSettingsView'
      security:
      - Authorization: []
      summary: Get user settings
      x-summary-source: derived
    patch:
      tags:
      - user-notification-settings
      operationId: update_2
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NotificationSettingsRequest'
        required: true
      responses:
        '200':
          description: update_2 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotificationSettingsView'
      security:
      - Authorization: []
      summary: Update 2
      x-summary-source: derived
components:
  schemas:
    NotificationSettingsRequest:
      required:
      - settings
      type: object
      properties:
        settings:
          properties:
            DAILY_DIGEST:
              $ref: '#/components/schemas/EnumMap_NotificationChannel.Boolean_'
            WEEKLY_DIGEST:
              $ref: '#/components/schemas/EnumMap_NotificationChannel.Boolean_'
            EVENT_CONFLICT:
              $ref: '#/components/schemas/EnumMap_NotificationChannel.Boolean_'
            EVENT_ABOUT_TO_START:
              $ref: '#/components/schemas/EnumMap_NotificationChannel.Boolean_'
            INVITED_TO_MEETING:
              $ref: '#/components/schemas/EnumMap_NotificationChannel.Boolean_'
            MEETING_UPDATED:
              $ref: '#/components/schemas/EnumMap_NotificationChannel.Boolean_'
            MEETING_CANCELLED:
              $ref: '#/components/schemas/EnumMap_NotificationChannel.Boolean_'
            APP_UPDATES:
              $ref: '#/components/schemas/EnumMap_NotificationChannel.Boolean_'
            EVENT_REMINDERS:
              $ref: '#/components/schemas/EnumMap_NotificationChannel.Boolean_'
        allowSlackNotificationsWithinDays:
          type:
          - integer
          - 'null'
          format: int32
    AbstractMap_NotificationChannel.Boolean_:
      type: object
      properties:
        empty:
          type: boolean
    EnumMap_NotificationChannel.Boolean_:
      $ref: '#/components/schemas/AbstractMap_NotificationChannel.Boolean_'
    NotificationSettingsView:
      required:
      - allowSlackNotificationsWithinDays
      - settings
      type: object
      properties:
        settings:
          properties:
            DAILY_DIGEST:
              $ref: '#/components/schemas/EnumMap_NotificationChannel.Boolean_'
            WEEKLY_DIGEST:
              $ref: '#/components/schemas/EnumMap_NotificationChannel.Boolean_'
            EVENT_CONFLICT:
              $ref: '#/components/schemas/EnumMap_NotificationChannel.Boolean_'
            EVENT_ABOUT_TO_START:
              $ref: '#/components/schemas/EnumMap_NotificationChannel.Boolean_'
            INVITED_TO_MEETING:
              $ref: '#/components/schemas/EnumMap_NotificationChannel.Boolean_'
            MEETING_UPDATED:
              $ref: '#/components/schemas/EnumMap_NotificationChannel.Boolean_'
            MEETING_CANCELLED:
              $ref: '#/components/schemas/EnumMap_NotificationChannel.Boolean_'
            APP_UPDATES:
              $ref: '#/components/schemas/EnumMap_NotificationChannel.Boolean_'
            EVENT_REMINDERS:
              $ref: '#/components/schemas/EnumMap_NotificationChannel.Boolean_'
        allowSlackNotificationsWithinDays:
          type: integer
          format: int32
  securitySchemes:
    Authorization:
      type: oauth2
