openapi: 3.0.1
info:
  title: Reclaim account-time-schemes changelog API
  description: Reclaim's awesome API
  contact:
    name: Reclaim.ai Inc.
    url: http://reclaim.ai
    email: info@reclaim.ai
  license:
    name: Reclaim 9.9
    url: http://reclaim.ai
  version: '0.1'
tags:
- name: changelog
paths:
  /api/changelog:
    get:
      tags:
      - changelog
      operationId: getChangeLog
      responses:
        '200':
          description: getChangeLog 200 response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ChangeLogEntryView'
      security:
      - Authorization: []
  /api/changelog/events:
    get:
      tags:
      - changelog
      operationId: events
      parameters:
      - name: eventIds
        in: query
        required: true
        schema:
          type: array
          items:
            type: string
      responses:
        '200':
          description: events 200 response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ChangeLogEntryView'
      security:
      - Authorization: []
  /api/changelog/scheduling-links:
    get:
      tags:
      - changelog
      operationId: schedulingLinks
      parameters:
      - name: schedulingLinkIds
        in: query
        required: true
        schema:
          type: array
          items:
            type: string
      responses:
        '200':
          description: schedulingLinks 200 response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ChangeLogEntryView'
      security:
      - Authorization: []
  /api/changelog/smart-habits:
    get:
      tags:
      - changelog
      operationId: habits
      parameters:
      - name: lineageIds
        in: query
        required: true
        schema:
          type: array
          items:
            type: integer
            format: int64
      responses:
        '200':
          description: habits 200 response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ChangeLogEntryView'
      security:
      - Authorization: []
  /api/changelog/smart-meetings:
    get:
      tags:
      - changelog
      operationId: meetings
      parameters:
      - name: lineageIds
        in: query
        required: true
        schema:
          type: array
          items:
            type: integer
            format: int64
      responses:
        '200':
          description: meetings 200 response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ChangeLogEntryView'
      security:
      - Authorization: []
  /api/changelog/tasks:
    get:
      tags:
      - changelog
      operationId: tasks
      parameters:
      - name: taskIds
        in: query
        required: true
        schema:
          type: array
          items:
            type: integer
            format: int64
      responses:
        '200':
          description: tasks 200 response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ChangeLogEntryView'
      security:
      - Authorization: []
components:
  schemas:
    ChangeLogEntryMetadataView:
      type: object
    ChangeLogReason:
      type: string
      enum:
      - SMART_1_1_SKIPPED
      - SMART_1_1_ATTENDEE_DECLINED
      - SMART_1_1_CREATED
      - SMART_1_1_ATTENDEE_AUTO_ACCEPTED
      - SMART_1_1_DELETED
      - SMART_1_1_ATTENDEE_RESCHEDULED
      - SMART_1_1_PIN
      - SMART_1_1_UNPIN
      - HABIT_START_NOW
      - HABIT_RESTART_NOW
      - HABIT_MOVED
      - HABIT_RESCHEDULED
      - HABIT_ENABLED
      - HABIT_DISABLED
      - HABIT_DELETED
      - HABIT_SKIPPED
      - HABIT_STOPPED
      - HABIT_MARKED_DONE
      - HABIT_UNPIN
      - HABIT_PIN
      - HABIT_CREATED
      - HABIT_PRIORITY_CHANGED
      - HABIT_TIME_POLICY_CHANGED
      - SMART_HABIT_START
      - SMART_HABIT_STOP
      - SMART_HABIT_RESCHEDULE
      - SMART_HABIT_RESET_SCHEDULE
      - SMART_HABIT_SKIP
      - SMART_HABIT_PIN
      - SMART_HABIT_UNPIN
      - SMART_HABIT_MOVE
      - SMART_HABIT_MARK_DONE
      - SMART_HABIT_RECORD
      - SMART_HABIT_SKIPPED_DUE_TO_RESERVED_WORD
      - SMART_HABIT_DECLINE
      - SMART_MEETING_RESCHEDULE
      - SMART_MEETING_RESET_SCHEDULE
      - SMART_MEETING_SKIP
      - SMART_MEETING_PIN
      - SMART_MEETING_UNPIN
      - SMART_MEETING_MOVE
      - SMART_MEETING_MARK_DONE
      - SMART_MEETING_DECLINE
      - SMART_SERIES_EVENT_REMOVED_DUE_TO_FORCE_SKIP
      - SMART_SERIES_EVENT_REMOVED_DUE_TO_NO_TIME
      - SMART_SERIES_EVENT_MOVED
      - SMART_SERIES_EVENT_NO_TIME_ORIGINAL
      - SMART_SERIES_EVENT_NO_TIME_LAST
      - SMART_SERIES_EVENT_NO_TIME_PARTIAL_PERIOD_REMOVED
      - SMART_SERIES_EVENT_NO_TIME_PARTIAL_PERIOD_PUNTED
      - TASK_PIN
      - TASK_UNPIN
      - TASK_START_NOW
      - EVENT_AUTO_LOCK_CHANGED
      - SCHEDULING_LINK_CREATED
      - SCHEDULING_LINK_DELETED
      - SCHEDULING_LINK_BRANDING_CREATED
      - SCHEDULING_LINK_BRANDING_UPDATED
      - SCHEDULING_LINK_BRANDING_DELETED
      - FOCUS_EVENT_PIN
      - FOCUS_EVENT_UNPIN
      - FOCUS_EVENT_RESCHEDULE
      - EVENT_DELETED_VIA_CALENDAR_ASSIGNMENT_SKIPPED_FOR_PERIOD
      - EVENT_DELETED_VIA_CALENDAR_ASSIGNMENT_SKIPPED_FOR_DAY
    ReclaimEventType:
      type: string
      enum:
      - USER
      - SYNC
      - HABIT_ASSIGNMENT
      - SMART_HABIT
      - ONE_ON_ONE_ASSIGNMENT
      - SMART_MEETING
      - TASK_ASSIGNMENT
      - CONF_BUFFER
      - TRAVEL_BUFFER
      - SCHEDULING_LINK_MEETING
      - UNKNOWN
      - FOCUS
    ChangeLogEntryView:
      required:
      - changedAt
      - id
      - reason
      type: object
      properties:
        id:
          type: integer
          format: int64
        changedAt:
          type: string
          format: date-time
        reclaimEventType:
          nullable: true
          allOf:
          - $ref: '#/components/schemas/ReclaimEventType'
        assignmentId:
          type: integer
          format: int64
          nullable: true
        assignmentSubId:
          type: integer
          format: int64
          nullable: true
        eventId:
          type: string
          nullable: true
        organizerId:
          type: string
          nullable: true
        actorId:
          type: string
          nullable: true
        reason:
          $ref: '#/components/schemas/ChangeLogReason'
        lockChangedMetadata:
          nullable: true
          allOf:
          - $ref: '#/components/schemas/ChangeLogEntryMetadataView'
        periodSkippedMetadata:
          nullable: true
          allOf:
          - $ref: '#/components/schemas/ChangeLogEntryMetadataView'
        eventMovedMetadata:
          nullable: true
          allOf:
          - $ref: '#/components/schemas/ChangeLogEntryMetadataView'
        periodSkippedDueToReservedWordMetadata:
          nullable: true
          allOf:
          - $ref: '#/components/schemas/ChangeLogEntryMetadataView'
  securitySchemes:
    Authorization:
      type: oauth2
