openapi: 3.2.0
info:
  title: Reclaim Scoring API
  description: Reclaim's awesome API
  contact:
    name: Reclaim.ai Inc.
    url: http://reclaim.ai
    email: info@reclaim.ai
  license:
    name: Reclaim 9.9
    url: http://reclaim.ai
  version: '0.1'
tags:
- name: Scoring
paths:
  /api/scoring/rescore:
    post:
      tags:
      - Scoring
      operationId: rescore
      responses:
        '200':
          description: rescore 200 response
          content:
            application/json:
              schema:
                type: object
      security:
      - Authorization: []
      summary: Rescore
      x-summary-source: derived
components:
  securitySchemes:
    Authorization:
      type: oauth2
