openapi: 3.2.0
info:
  title: Reclaim Clickup API
  description: Reclaim's awesome API
  contact:
    name: Reclaim.ai Inc.
    url: http://reclaim.ai
    email: info@reclaim.ai
  license:
    name: Reclaim 9.9
    url: http://reclaim.ai
  version: '0.1'
tags:
- name: clickup
paths:
  /api/clickup/integrations:
    get:
      tags:
      - clickup
      operationId: integrations_2
      responses:
        '200':
          description: integrations_2 200 response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ClickUpIntegration'
      deprecated: true
      security:
      - Authorization: []
      summary: Integrations 2
      x-summary-source: derived
    delete:
      tags:
      - clickup
      operationId: deleteIntegration_1
      responses:
        '200':
          description: deleteIntegration_1 200 response
          content:
            application/json:
              schema:
                type: object
      security:
      - Authorization: []
      summary: Delete integration 1
      x-summary-source: derived
  /api/clickup/integrations/details:
    get:
      tags:
      - clickup
      operationId: clickUpIntegrationsDetails
      responses:
        '200':
          description: clickUpIntegrationsDetails 200 response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ClickUpIntegrationDetails'
      security:
      - Authorization: []
      summary: Click up integrations details
      x-summary-source: derived
  /api/clickup/integrations/settings/{workspaceId}:
    patch:
      tags:
      - clickup
      operationId: patchIntegration
      parameters:
      - name: workspaceId
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClickUpIntegrationPatch'
        required: true
      responses:
        '200':
          description: patchIntegration 200 response
          content:
            application/json:
              schema:
                type: object
      security:
      - Authorization: []
      summary: Patch integration
      x-summary-source: derived
  /api/clickup/integrations/{workspaceId}:
    patch:
      tags:
      - clickup
      operationId: patchIntegration_1
      parameters:
      - name: workspaceId
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeprecatedClickUpIntegrationPatch'
        required: true
      responses:
        '200':
          description: patchIntegration_1 200 response
          content:
            application/json:
              schema:
                type: object
      deprecated: true
      security:
      - Authorization: []
      summary: Patch integration 1
      x-summary-source: derived
  /web/clickup/task/{taskId}:
    get:
      tags:
      - clickup
      operationId: taskDetails_1
      parameters:
      - name: taskId
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: taskDetails_1 200 response
          content:
            application/json:
              schema:
                type: object
      summary: Task details 1
      x-summary-source: derived
components:
  schemas:
    ClickUpResource:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        withId:
          type: string
        withName:
          type: string
        equals: {}
        hashCode:
          type: integer
          format: int32
        toString:
          type: string
    AbstractCollection_ClickUpStatus_:
      type: object
      properties:
        empty:
          type: boolean
    ClickUpIntegration:
      type: object
      properties:
        workspace:
          $ref: '#/components/schemas/ClickUpResource'
        available_spaces:
          $ref: '#/components/schemas/ImmutableSet_ClickUpSpace_'
        selected_space_ids:
          $ref: '#/components/schemas/ImmutableSet_String_'
        requires_tag:
          type: boolean
        withWorkspace:
          $ref: '#/components/schemas/ClickUpResource'
        withAvailable_spaces:
          type: array
          items:
            $ref: '#/components/schemas/ClickUpSpace'
        withSelected_space_ids:
          type: array
          items:
            type: string
        withRequires_tag:
          type: boolean
        equals: {}
        hashCode:
          type: integer
          format: int32
        toString:
          type: string
    ClickUpSpace:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        features:
          type: object
          additionalProperties: true
        statuses:
          $ref: '#/components/schemas/ImmutableList_ClickUpStatus_'
        withId:
          type: string
        withName:
          type: string
        withFeatures:
          type: object
          additionalProperties: true
        withStatuses:
          type: array
          items:
            $ref: '#/components/schemas/ClickUpStatus'
        equals: {}
        hashCode:
          type: integer
          format: int32
        toString:
          type: string
    AbstractCollection_ClickUpSpace_:
      type: object
      properties:
        empty:
          type: boolean
    ImmutableCollection_ClickUpStatus_:
      type: object
      allOf:
      - $ref: '#/components/schemas/AbstractCollection_ClickUpStatus_'
      - properties:
          empty:
            type: boolean
          partialView:
            type: boolean
    ClickUpSpaceWithEligibility:
      required:
      - features
      - id
      - isEligible
      - name
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        isEligible:
          type: boolean
        features:
          type: object
          additionalProperties: true
    ClickUpStatusType:
      type: string
      enum:
      - open
      - done
      - closed
      - custom
      - unstarted
      - active
      x-enum-varnames:
      - open
      - done
      - closed
      - custom
      - unstarted
      - active
    ClickUpIntegrationDetails:
      required:
      - availableSpaces
      - tags
      - titleFormat
      - workspace
      type: object
      properties:
        workspace:
          $ref: '#/components/schemas/ClickUpResource'
        availableSpaces:
          type: array
          items:
            $ref: '#/components/schemas/ClickUpSpaceWithEligibility'
        tags:
          type: array
          items:
            type: string
        lastSynced:
          type:
          - string
          - 'null'
          format: date-time
        titleFormat:
          $ref: '#/components/schemas/ClickUpTitleFormat'
        bypassTimeTracking:
          type:
          - boolean
          - 'null'
    ImmutableList_ClickUpStatus_:
      type: object
      allOf:
      - $ref: '#/components/schemas/ImmutableCollection_ClickUpStatus_'
      - $ref: '#/components/schemas/AbstractCollection_ClickUpStatus_'
      - properties:
          empty:
            type: boolean
          first:
            $ref: '#/components/schemas/ClickUpStatus'
          last:
            $ref: '#/components/schemas/ClickUpStatus'
    ClickUpTitleFormat:
      type: string
      enum:
      - TASK_TITLE_ONLY
      - TASK_TITLE_THEN_LIST
      - TASK_TITLE_THEN_LIST_THEN_SPACE
      - TASK_TITLE_THEN_SPACE
      - SPACE_NAME_THEN_TASK_TITLE
    ImmutableSet_String_:
      type: object
      allOf:
      - $ref: '#/components/schemas/ImmutableCollection_String_'
      - $ref: '#/components/schemas/AbstractCollection_String_'
      - properties:
          empty:
            type: boolean
          hashCodeFast:
            type: boolean
    ClickUpIntegrationPatch:
      type: object
      properties:
        titleFormat:
          allOf:
          - $ref: '#/components/schemas/ClickUpTitleFormat'
        bypassTimeTracking:
          type:
          - boolean
          - 'null'
        withTitleFormat:
          $ref: '#/components/schemas/ClickUpTitleFormat'
        withBypassTimeTracking:
          type: boolean
        equals: {}
        hashCode:
          type: integer
          format: int32
        toString:
          type: string
    AbstractCollection_String_:
      type: object
      properties:
        empty:
          type: boolean
    ImmutableCollection_String_:
      type: object
      allOf:
      - $ref: '#/components/schemas/AbstractCollection_String_'
      - properties:
          empty:
            type: boolean
          partialView:
            type: boolean
    ImmutableCollection_ClickUpSpace_:
      type: object
      allOf:
      - $ref: '#/components/schemas/AbstractCollection_ClickUpSpace_'
      - properties:
          empty:
            type: boolean
          partialView:
            type: boolean
    DeprecatedClickUpIntegrationPatch:
      type: object
      properties:
        selected_space_ids:
          $ref: '#/components/schemas/ImmutableSet_String_'
        requires_tag:
          type: boolean
        withSelected_space_ids:
          type: array
          items:
            type: string
        withRequires_tag:
          type: boolean
        equals: {}
        hashCode:
          type: integer
          format: int32
        toString:
          type: string
      deprecated: true
    ClickUpStatus:
      type: object
      properties:
        status:
          type: string
        orderindex:
          type: integer
          format: int32
        type:
          $ref: '#/components/schemas/ClickUpStatusType'
        color:
          type:
          - string
          - 'null'
        withStatus:
          type: string
        withOrderindex:
          type: integer
          format: int32
        withType:
          $ref: '#/components/schemas/ClickUpStatusType'
        withColor:
          type: string
        equals: {}
        hashCode:
          type: integer
          format: int32
        toString:
          type: string
    ImmutableSet_ClickUpSpace_:
      type: object
      allOf:
      - $ref: '#/components/schemas/ImmutableCollection_ClickUpSpace_'
      - $ref: '#/components/schemas/AbstractCollection_ClickUpSpace_'
      - properties:
          empty:
            type: boolean
          hashCodeFast:
            type: boolean
  securitySchemes:
    Authorization:
      type: oauth2
