openapi: 3.2.0
info:
  title: Reclaim Tasks API
  description: Reclaim's awesome API
  contact:
    name: Reclaim.ai Inc.
    url: http://reclaim.ai
    email: info@reclaim.ai
  license:
    name: Reclaim 9.9
    url: http://reclaim.ai
  version: '0.1'
tags:
- name: reclaim-tasks
paths:
  /api/reclaim-tasks:
    get:
      tags:
      - reclaim-tasks
      operationId: listReclaimTasks
      parameters:
      - name: query
        in: query
        schema:
          type:
          - string
          - 'null'
      - name: completed
        in: query
        schema:
          type:
          - boolean
          - 'null'
      responses:
        '200':
          description: listReclaimTasks 200 response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ReclaimTask'
      deprecated: true
      security:
      - Authorization: []
      summary: List reclaim tasks
      x-summary-source: derived
    post:
      tags:
      - reclaim-tasks
      operationId: createReclaimTask
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateReclaimTaskRequest'
        required: true
      responses:
        '200':
          description: createReclaimTask 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReclaimTask'
      security:
      - Authorization: []
      summary: Create reclaim task
      x-summary-source: derived
  /api/reclaim-tasks/page:
    get:
      tags:
      - reclaim-tasks
      operationId: listReclaimTaskPage
      parameters:
      - name: query
        in: query
        schema:
          type:
          - string
          - 'null'
      - name: sort
        in: query
        schema:
          allOf:
          - $ref: '#/components/schemas/ReclaimTaskSortField'
      - name: relativeDue
        in: query
        schema:
          allOf:
          - $ref: '#/components/schemas/ReclaimTaskRelativeDue'
      - name: completed
        in: query
        schema:
          type:
          - boolean
          - 'null'
      - name: dueBefore
        in: query
        schema:
          type:
          - string
          - 'null'
          format: date
      - name: dueAfter
        in: query
        schema:
          type:
          - string
          - 'null'
          format: date
      - name: overdue
        in: query
        schema:
          type:
          - boolean
          - 'null'
      - name: hasDuration
        in: query
        schema:
          type:
          - boolean
          - 'null'
      - name: after
        in: query
        schema:
          type:
          - string
          - 'null'
      - name: order
        in: query
        schema:
          allOf:
          - $ref: '#/components/schemas/SortOrder'
      - name: count
        in: query
        schema:
          type:
          - integer
          - 'null'
          format: int32
      responses:
        '200':
          description: listReclaimTaskPage 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Page_ReclaimTaskView_'
      security:
      - Authorization: []
      summary: List reclaim task page
      x-summary-source: derived
  /api/reclaim-tasks/{id}:
    get:
      tags:
      - reclaim-tasks
      operationId: getReclaimTask
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        '200':
          description: getReclaimTask 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReclaimTask'
      security:
      - Authorization: []
      summary: Get reclaim task
      x-summary-source: derived
    delete:
      tags:
      - reclaim-tasks
      operationId: deleteReclaimTask
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        '200':
          description: deleteReclaimTask 200 response
      security:
      - Authorization: []
      summary: Delete reclaim task
      x-summary-source: derived
    patch:
      tags:
      - reclaim-tasks
      operationId: updateReclaimTask
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateReclaimTaskRequest'
        required: true
      responses:
        '200':
          description: updateReclaimTask 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReclaimTask'
      security:
      - Authorization: []
      summary: Update reclaim task
      x-summary-source: derived
components:
  schemas:
    Page_ReclaimTaskView_:
      required:
      - count
      - first
      - hasNextPage
      - items
      - last
      - order
      type: object
      properties:
        first:
          type: string
        last:
          type: string
        order:
          $ref: '#/components/schemas/SortOrder'
        count:
          type: integer
          format: int32
        hasNextPage:
          type: boolean
        items:
          type: array
          items:
            $ref: '#/components/schemas/ReclaimTask'
        totalCount:
          type:
          - integer
          - 'null'
          format: int64
    PriorityLevel:
      type: string
      enum:
      - P1
      - P2
      - P3
      - P4
      - PRIORITIZE
      - DEFAULT
      x-deprecated:
      - PRIORITIZE
      - DEFAULT
    ReclaimTaskRelativeDue:
      type: string
      enum:
      - TODAY
      - THIS_WEEK
      - THIS_MONTH
    CreateReclaimTaskRequest:
      required:
      - title
      type: object
      properties:
        title:
          type: string
        dueDate:
          type:
          - string
          - 'null'
          format: date
        startDate:
          type:
          - string
          - 'null'
          format: date
        estimateMinutes:
          type:
          - integer
          - 'null'
          format: int32
        priority:
          allOf:
          - $ref: '#/components/schemas/PriorityLevel'
    GtdTaskLink:
      required:
      - url
      type: object
      properties:
        url:
          type: string
    ReclaimTask:
      required:
      - completed
      - extendedProperties
      - id
      - title
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type:
          - string
          - 'null'
        priority:
          allOf:
          - $ref: '#/components/schemas/PriorityLevel'
        status:
          type:
          - string
          - 'null'
        link:
          allOf:
          - $ref: '#/components/schemas/GtdTaskLink'
        due:
          type:
          - string
          - 'null'
          format: date-time
        start:
          type:
          - string
          - 'null'
          format: date-time
        completed:
          type: boolean
        estimateMinutes:
          type:
          - integer
          - 'null'
          format: int32
        extendedProperties:
          type: object
          additionalProperties: true
        type:
          type: string
    SortOrder:
      type: string
      enum:
      - ASCENDING
      - DESCENDING
      - UNSORTED
    ReclaimTaskSortField:
      type: string
      enum:
      - DUE_DATE
      - NAME
      - PRIORITY
    UpdateReclaimTaskRequest:
      type: object
      properties:
        title:
          type:
          - string
          - 'null'
        dueDate:
          type:
          - string
          - 'null'
          format: date
        startDate:
          type:
          - string
          - 'null'
          format: date
        completed:
          type:
          - boolean
          - 'null'
        estimateMinutes:
          type:
          - integer
          - 'null'
          format: int32
        priority:
          allOf:
          - $ref: '#/components/schemas/PriorityLevel'
  securitySchemes:
    Authorization:
      type: oauth2
